"""structured organization address (ADR-007)

Revision ID: 485f37aa7554
Revises: b2e4f6a8c0d1
Create Date: 2026-05-01 14:50:29.026098
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485f37aa7554'
down_revision: Union[str, None] = 'b2e4f6a8c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(length=2), server_default='US', nullable=False))
    op.drop_column('organizations', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address_line2')
    op.drop_column('organizations', 'address_line1')
    # ### end Alembic commands ###
