"""initial schema

Revision ID: a68701f39fed
Revises: 
Create Date: 2026-04-16 23:58:19.906516
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a68701f39fed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('npi_number', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('people',
    sa.Column('auth_subject', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('auth_subject', name=op.f('uq_people_auth_subject')),
    sa.UniqueConstraint('email', name=op.f('uq_people_email'))
    )
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_person_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_person_id'], ['people.id'], name=op.f('fk_audit_logs_actor_person_id_people')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('consent_types',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_system_type', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_consent_types_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_types')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_consent_types_organization_id_slug'))
    )
    op.create_table('cpt_codes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('default_rate_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_cpt_codes_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cpt_codes')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_cpt_codes_organization_id_code'))
    )
    op.create_table('document_types',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('linked_resource_table', sa.String(), nullable=True),
    sa.Column('is_system_type', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_types_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_document_types_organization_id_slug'))
    )
    op.create_table('entity_types',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_system_type', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_person_subtype', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entity_types_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_types')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_entity_types_organization_id_slug'))
    )
    op.create_table('form_templates',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('form_type', sa.Enum('INTAKE', 'ASSESSMENT', 'CONSENT', 'CUSTOM', name='formtype', native_enum=False), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(), server_default='1.0.0', nullable=False),
    sa.Column('is_system_template', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_form_templates_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_templates')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_form_templates_organization_id_slug'))
    )
    op.create_table('icd_codes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_icd_codes_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icd_codes')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_icd_codes_organization_id_code'))
    )
    op.create_table('insurance_payers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('payer_id', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_insurance_payers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_payers'))
    )
    op.create_table('permissions',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('resource_slug', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_permission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_permissions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_permissions_organization_id_slug'))
    )
    op.create_table('roles',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('primary_domain', sa.Enum('ADMIN', 'PROVIDER', 'CLIENT', name='roledomain', native_enum=False), nullable=False),
    sa.Column('parent_role_id', sa.UUID(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], name=op.f('fk_roles_parent_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_roles_organization_id_slug'))
    )
    op.create_table('appointment_types',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('cpt_code_id', sa.UUID(), nullable=True),
    sa.Column('is_telehealth', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_intake', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cpt_code_id'], ['cpt_codes.id'], name=op.f('fk_appointment_types_cpt_code_id_cpt_codes')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_appointment_types_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_types'))
    )
    op.create_table('documents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_person_id', sa.UUID(), nullable=False),
    sa.Column('linked_resource_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_documents_document_type_id_document_types')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations')),
    sa.ForeignKeyConstraint(['uploaded_by_person_id'], ['people.id'], name=op.f('fk_documents_uploaded_by_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_table('entity_attributes',
    sa.Column('entity_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'BOOL', 'ENUM', 'FK', 'JSONB', name='fieldtype', native_enum=False), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_types.id'], name=op.f('fk_entity_attributes_entity_type_id_entity_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_attributes'))
    )
    op.create_table('entity_instances',
    sa.Column('entity_type_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_types.id'], name=op.f('fk_entity_instances_entity_type_id_entity_types')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entity_instances_organization_id_organizations')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_entity_instances_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_instances'))
    )
    op.create_table('role_permissions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('granted_by_person_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_person_id'], ['people.id'], name=op.f('fk_role_permissions_granted_by_person_id_people')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_role_permissions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions'))
    )
    op.create_index('uq_role_permissions_active', 'role_permissions', ['organization_id', 'role_id', 'permission_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('attribute_values',
    sa.Column('entity_instance_id', sa.UUID(), nullable=False),
    sa.Column('entity_attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entity_attribute_id'], ['entity_attributes.id'], name=op.f('fk_attribute_values_entity_attribute_id_entity_attributes')),
    sa.ForeignKeyConstraint(['entity_instance_id'], ['entity_instances.id'], name=op.f('fk_attribute_values_entity_instance_id_entity_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_values')),
    sa.UniqueConstraint('entity_instance_id', 'entity_attribute_id', name=op.f('uq_attribute_values_entity_instance_id_entity_attribute_id'))
    )
    op.create_table('client_consents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_instance_id', sa.UUID(), nullable=False),
    sa.Column('consent_type_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', 'REVOKED', 'EXPIRED', name='consentstatus', native_enum=False), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_person_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_person_id', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('form_template_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_instance_id'], ['entity_instances.id'], name=op.f('fk_client_consents_client_instance_id_entity_instances')),
    sa.ForeignKeyConstraint(['consent_type_id'], ['consent_types.id'], name=op.f('fk_client_consents_consent_type_id_consent_types')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_client_consents_document_id_documents')),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], name=op.f('fk_client_consents_form_template_id_form_templates')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_client_consents_organization_id_organizations')),
    sa.ForeignKeyConstraint(['revoked_by_person_id'], ['people.id'], name=op.f('fk_client_consents_revoked_by_person_id_people')),
    sa.ForeignKeyConstraint(['signed_by_person_id'], ['people.id'], name=op.f('fk_client_consents_signed_by_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_consents'))
    )
    op.create_table('client_insurances',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_instance_id', sa.UUID(), nullable=False),
    sa.Column('insurance_payer_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('group_number', sa.String(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('priority', sa.Enum('PRIMARY', 'SECONDARY', name='insurancepriority', native_enum=False), nullable=False),
    sa.Column('copay_cents', sa.Integer(), nullable=True),
    sa.Column('deductible_cents', sa.Integer(), nullable=True),
    sa.Column('deductible_met_cents', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_instance_id'], ['entity_instances.id'], name=op.f('fk_client_insurances_client_instance_id_entity_instances')),
    sa.ForeignKeyConstraint(['insurance_payer_id'], ['insurance_payers.id'], name=op.f('fk_client_insurances_insurance_payer_id_insurance_payers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_client_insurances_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_insurances'))
    )
    op.create_index('uq_client_insurances_active_priority', 'client_insurances', ['organization_id', 'client_instance_id', 'insurance_payer_id', 'priority'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('person_roles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('entity_instance_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('assigned_by_person_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_person_id'], ['people.id'], name=op.f('fk_person_roles_assigned_by_person_id_people')),
    sa.ForeignKeyConstraint(['entity_instance_id'], ['entity_instances.id'], name=op.f('fk_person_roles_entity_instance_id_entity_instances')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_person_roles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_person_roles_person_id_people')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_person_roles_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_roles'))
    )
    op.create_index('uq_person_roles_active', 'person_roles', ['organization_id', 'person_id', 'role_id', 'entity_instance_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('sessions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type_id', sa.UUID(), nullable=False),
    sa.Column('provider_instance_id', sa.UUID(), nullable=False),
    sa.Column('client_instance_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='sessionstatus', native_enum=False), server_default='SCHEDULED', nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_person_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], name=op.f('fk_sessions_appointment_type_id_appointment_types')),
    sa.ForeignKeyConstraint(['cancelled_by_person_id'], ['people.id'], name=op.f('fk_sessions_cancelled_by_person_id_people')),
    sa.ForeignKeyConstraint(['client_instance_id'], ['entity_instances.id'], name=op.f('fk_sessions_client_instance_id_entity_instances')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sessions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['provider_instance_id'], ['entity_instances.id'], name=op.f('fk_sessions_provider_instance_id_entity_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('clinical_notes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('author_instance_id', sa.UUID(), nullable=False),
    sa.Column('note_format', sa.Enum('SOAP', 'DAP', 'BIRP', name='noteformat', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SIGNED', 'COSIGNED', 'AMENDMENT_PENDING', name='notestatus', native_enum=False), server_default='DRAFT', nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_person_id', sa.UUID(), nullable=True),
    sa.Column('cosigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cosigned_by_person_id', sa.UUID(), nullable=True),
    sa.Column('cosign_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('amendment_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_instance_id'], ['entity_instances.id'], name=op.f('fk_clinical_notes_author_instance_id_entity_instances')),
    sa.ForeignKeyConstraint(['cosigned_by_person_id'], ['people.id'], name=op.f('fk_clinical_notes_cosigned_by_person_id_people')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_clinical_notes_organization_id_organizations')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_clinical_notes_session_id_sessions')),
    sa.ForeignKeyConstraint(['signed_by_person_id'], ['people.id'], name=op.f('fk_clinical_notes_signed_by_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_notes')),
    sa.UniqueConstraint('session_id', name=op.f('uq_clinical_notes_session_id'))
    )
    op.create_table('invoices',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('client_instance_id', sa.UUID(), nullable=False),
    sa.Column('provider_instance_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIAL', 'PAID', 'VOID', name='invoicestatus', native_enum=False), server_default='DRAFT', nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('balance_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_person_id', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_instance_id'], ['entity_instances.id'], name=op.f('fk_invoices_client_instance_id_entity_instances')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invoices_organization_id_organizations')),
    sa.ForeignKeyConstraint(['provider_instance_id'], ['entity_instances.id'], name=op.f('fk_invoices_provider_instance_id_entity_instances')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_invoices_session_id_sessions')),
    sa.ForeignKeyConstraint(['voided_by_person_id'], ['people.id'], name=op.f('fk_invoices_voided_by_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index('uq_invoices_active_per_session', 'invoices', ['session_id'], unique=True, postgresql_where=sa.text("status != 'void'"))
    op.create_table('invoice_line_items',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('cpt_code_id', sa.UUID(), nullable=False),
    sa.Column('icd_code_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit_rate_cents', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cpt_code_id'], ['cpt_codes.id'], name=op.f('fk_invoice_line_items_cpt_code_id_cpt_codes')),
    sa.ForeignKeyConstraint(['icd_code_id'], ['icd_codes.id'], name=op.f('fk_invoice_line_items_icd_code_id_icd_codes')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invoice_line_items_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items'))
    )
    op.create_table('payments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CHECK', 'CARD', 'ACH', 'INSURANCE', 'OTHER', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('payer_type', sa.Enum('CLIENT', 'INSURANCE', 'OTHER', name='payertype', native_enum=False), nullable=False),
    sa.Column('insurance_payer_id', sa.UUID(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_person_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('POSTED', 'VOIDED', name='paymentstatus', native_enum=False), server_default='POSTED', nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_person_id', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['insurance_payer_id'], ['insurance_payers.id'], name=op.f('fk_payments_insurance_payer_id_insurance_payers')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['recorded_by_person_id'], ['people.id'], name=op.f('fk_payments_recorded_by_person_id_people')),
    sa.ForeignKeyConstraint(['voided_by_person_id'], ['people.id'], name=op.f('fk_payments_voided_by_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('invoice_line_items')
    op.drop_index('uq_invoices_active_per_session', table_name='invoices', postgresql_where=sa.text("status != 'void'"))
    op.drop_table('invoices')
    op.drop_table('clinical_notes')
    op.drop_table('sessions')
    op.drop_index('uq_person_roles_active', table_name='person_roles', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('person_roles')
    op.drop_index('uq_client_insurances_active_priority', table_name='client_insurances', postgresql_where=sa.text('is_active = true'))
    op.drop_table('client_insurances')
    op.drop_table('client_consents')
    op.drop_table('attribute_values')
    op.drop_index('uq_role_permissions_active', table_name='role_permissions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('role_permissions')
    op.drop_table('entity_instances')
    op.drop_table('entity_attributes')
    op.drop_table('documents')
    op.drop_table('appointment_types')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('insurance_payers')
    op.drop_table('icd_codes')
    op.drop_table('form_templates')
    op.drop_table('entity_types')
    op.drop_table('document_types')
    op.drop_table('cpt_codes')
    op.drop_table('consent_types')
    op.drop_table('audit_logs')
    op.drop_table('people')
    op.drop_table('organizations')
    # ### end Alembic commands ###
